# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows

name: "build-and-deploy.yml"
on:
 push:
  branches:
   - main
jobs:
 build-and-deploy:
  name: "build-and-deploy"
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout"
     uses: actions/checkout@v2
     with:
      token: ${{ secrets.ACCESS_TOKEN }}
   - name: Setup NodeJs 12.x
     uses: actions/setup-node@v1
     with:
      node-version: 12.x
   - name: Setup Python 3.x
     uses: actions/setup-python@v1
     with:
      python-version: 3.x
   - name: "Build and Deploy"
     env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      USERS_COVER: ${{ secrets.USERS_COVER }}
     run: |
      echo "${USERS_COVER}" > ./config.json;
      python "./.github/workflows/build-and-deploy.py";
