# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows

name: "build-and-deploy"
on:
 push:
  branches:
   - main
jobs:
 build-and-deploy:
  name: "构建与部署"
  runs-on: ubuntu-latest
  steps:
   - name: "检查更新资源"
     uses: actions/checkout@v2
     with:
      token: ${{ secrets.ACCESS_TOKEN }}
   - name: "安装 NodeJs 12.x 环境"
     uses: actions/setup-node@v2
     with:
      node-version: 12.x
   - name: "安装 Python 3.x 环境"
     uses: actions/setup-python@v2
     with:
      python-version: 3.x
   - name: "设置默认时区"
     run: |
      sudo timedatectl set-timezone "Asia/Shanghai";
   - name: "安装 Python 依赖项"
     run: |
      pip install "requests==2.20.0";
   - name: "开始工作"
     env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      USERS_COVER: ${{ secrets.USERS_COVER }}
     run: |
      echo "${USERS_COVER}" > ./config.json;
      python "./.github/workflows/build-and-deploy.py";
   - name: "结束工作"
     run: |
      pip freeze > "./.github/workflows/requirements.txt";
      cat "./.github/workflows/requirements.txt";
      zip -r main.zip * .[^.]*;
      ls -AFR1 --group-directories-first;
      git config --global user.name "lyk082401";
      git config --global user.email "lyk082401@qq.com";
      git add .;
      git commit -m "Update repository files";
      git push -u origin main;
