# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows

name: "build-and-deploy"

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main
   page_build:
   release:
      types:
         - created
   workflow_dispatch:

jobs:
   init-env:
      name: "初始化运行环境"
      runs-on: ubuntu-latest
      steps:
         - name: "Checkout"
           uses: actions/checkout@v2
           with:
              token: ${{ secrets.ACCESS_TOKEN }}
         - name: "安装 NodeJs 12.x 环境"
           uses: actions/setup-node@v2
           with:
              node-version: 12.x
         - name: "安装 Python 3.x 环境"
           uses: actions/setup-python@v2
           with:
              python-version: 3.x
         - name: "设置默认时区"
           run: |
              sudo timedatectl set-timezone "Asia/Shanghai";
         - name: "安装 Python 依赖项"
           run: |
              pip install "requests==2.20.0";
   dump-env:
      name: "打印环境信息"
      runs-on: ubuntu-latest
      steps:
         - name: "Checkout"
           uses: actions/checkout@v2
           with:
              token: ${{ secrets.GITHUB_TOKEN }}
         - name: "Dump info"
           env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
              ENV_CONTEXT: ${{ toJSON(env) }}
              JOB_CONTEXT: ${{ toJSON(job) }}
              STEPS_CONTEXT: ${{ toJSON(steps) }}
              RUNNER_CONTEXT: ${{ toJSON(runner) }}
              SECRETS_CONTEXT: ${{ toJSON(secrets) }}
              STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
              MATRIX_CONTEXT: ${{ toJSON(matrix) }}
              NEEDS_CONTEXT: ${{ toJSON(needs) }}
           run: |
              contextinfos_file="./.github/workflows/contextinfos.txt";
              echo -e "[github]\n${GITHUB_CONTEXT}" > "${contextinfos_file}";
              echo -e "[env]\n${ENV_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[job]\n${JOB_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[steps]\n${STEPS_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[runner]\n${RUNNER_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[secrets]\n${SECRETS_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[strategy]\n${STRATEGY_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[matrix]\n${MATRIX_CONTEXT}" >> "${contextinfos_file}";
              echo -e "[needs]\n${NEEDS_CONTEXT}" >> "${contextinfos_file}";
   start-working:
      name: "开始工作"
      runs-on: ubuntu-latest
      needs: [init-env, dump-env]
      steps:
         - name: "Checkout"
           uses: actions/checkout@v2
           with:
              token: ${{ secrets.ACCESS_TOKEN }}
         - name: "Start working"
           env:
              ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           run: |
              # python "./.github/workflows/build-and-deploy.py";
   finish-worked:
      name: "结束工作"
      runs-on: ubuntu-latest
      needs: [init-env, dump-env, start-working]
      steps:
         - name: "Checkout"
           uses: actions/checkout@v2
           with:
              token: ${{ secrets.ACCESS_TOKEN }}
         - name: "Finish worked"
           run: |
              requirements_file="./.github/workflows/requirements.txt";
              work_time="$(date '+%Y%m%d%H%M%S')";
              main_zip_file="./main-${work_time}.zip";
              pip freeze > "${requirements_file}";
              zip -r "${main_zip_file}" * .[^.]*;
              git config --global user.name "lyk082401";
              git config --global user.email "lyk082401@qq.com";
              git add .;
              git commit -m "[${work_time}] 更新仓库备份文件";
              git branch -f dev;
              #git checkout main;
              git push -u main dev;
   # save-backup-file:
      # name: "保存备份文件"
      # runs-on: ubuntu-latest
      # needs: [init-env, dump-env, start-working, finish-worked]
      # steps:
         # - name: "Checkout"
           # uses: actions/checkout@v2
           # with:
              # token: ${{ secrets.ACCESS_TOKEN }}
         # - name: "Save backup"
           # # if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
           # run: |
              # 
              # 
              # # git init;
              # # git add .;
              # 
              # 
              # # git remote add origin https://github.com/cotools/cotools.github.io.git;
              # # git pull --rebase origin main;
              # 
