# Events that trigger workflows: https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
# Personal Access Tokens: https://github.com/settings/tokens
# Repository Actions Secrets: https://github.com/cotools/cotools.github.io/settings/secrets/actions

name: "on-push"

on:
   push:
      branches:
         - main
   # pull_request:
      # branches:
         # - main
   # page_build:
   # release:
      # types:
         # - created
   workflow_dispatch:

jobs:
   on-push:
      name: "On Push"
      runs-on: ubuntu-latest
      steps:
         - name: "[init] Checkout"
           uses: actions/checkout@v2
           with:
              token: ${{ secrets.ACCESS_TOKEN }}
         # - name: "[init] 安装 NodeJs 12.x 环境"
           # uses: actions/setup-node@v2
           # with:
              # node-version: 12.x
         # - name: "[init] 安装 Python 3.x 环境"
           # uses: actions/setup-python@v2
           # with:
              # python-version: 3.x
         # - name: "[init] 设置默认时区"
           # run: |
              # sudo timedatectl set-timezone "Asia/Shanghai";
         # - name: "[init] 安装 Python 依赖项"
           # run: |
              # pip install "requests==2.20.0";
         # - name: "[starting] Start working"
           # env:
              # GITHUB_TOKEN: ${{ secrets.github_token }}
              # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           # run: |
              # # python "./.github/workflows/on-push.py";
         - name: "[finished] Finish worked"
           env:
              CONTEXT_GITHUB: ${{ toJSON(github) }}
              CONTEXT_ENV: ${{ toJSON(env) }}
              CONTEXT_JOB: ${{ toJSON(job) }}
              CONTEXT_STEPS: ${{ toJSON(steps) }}
              CONTEXT_RUNNER: ${{ toJSON(runner) }}
              CONTEXT_SECRETS: ${{ toJSON(secrets) }}
              CONTEXT_STRATEGY: ${{ toJSON(strategy) }}
              CONTEXT_MATRIX: ${{ toJSON(matrix) }}
              CONTEXT_NEEDS: ${{ toJSON(needs) }}
              DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
              MASTER_BRANCH: ${{ github.event.repository.master_branch }}
              CLONE_URL: ${{ github.event.repository.clone_url }}
           run: |
              work_date="$(date '+%Y-%m-%d %H:%M:%S')";
              work_time="$(date '+%Y%m%d%H%M%S')";
              base_path="./.github/workflows";
              branch_local="main";
              branch_remote="dev";
              contextinfos_file="${base_path}/${branch_local}-contextinfos-${work_time}.txt";
              requirements_file="${base_path}/${branch_local}-requirements-${work_time}.txt";
              release_file="${base_path}/${branch_local}-release-${work_time}.zip";
              echo -e "\t打印环境上下文";
              echo -e "[github]\n${CONTEXT_GITHUB}" > "${contextinfos_file}";
              echo -e "[env]\n${CONTEXT_ENV}" >> "${contextinfos_file}";
              echo -e "[job]\n${CONTEXT_JOB}" >> "${contextinfos_file}";
              echo -e "[steps]\n${CONTEXT_STEPS}" >> "${contextinfos_file}";
              echo -e "[runner]\n${CONTEXT_RUNNER}" >> "${contextinfos_file}";
              echo -e "[secrets]\n${CONTEXT_SECRETS}" >> "${contextinfos_file}";
              echo -e "[strategy]\n${CONTEXT_STRATEGY}" >> "${contextinfos_file}";
              echo -e "[matrix]\n${CONTEXT_MATRIX}" >> "${contextinfos_file}";
              echo -e "[needs]\n${CONTEXT_NEEDS}" >> "${contextinfos_file}";
              echo -e "\t打印 Python 依赖包";
              pip freeze > "${requirements_file}";
              echo -e "\t生成最新资源包";
              zip -q -r "${release_file}" * .[^.]*;
              git config --global user.name "lyk082401";
              git config --global user.email "lyk082401@qq.com";
              echo -e "\t用户信息";
              git config --list;
              echo -e "\t本地状态";
              git status;
              echo -e "\t远程信息";
              git remote -v;
              echo -e "\t添加当前目录文件到暂存区中";
              git add .;
              echo -e "\t提交暂存区文件到本地仓库中";
              git commit --message "[${work_time}] 更新仓库备份文件";
              echo -e "\t尝试创建远程分支 ${branch_remote}";
              git branch --force "${branch_remote}";
              echo -e "\t将本地分支 ${branch_local} 推送到远程分支 ${branch_remote}";
              git push origin --force "${branch_local}:${branch_remote}";
