# Events that trigger workflows: https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
# Workflow syntax for GitHub Actions: https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions
# Personal Access Tokens: https://github.com/settings/tokens/new
# Repository Actions Secrets: https://github.com/cotools/cotools.github.io/settings/secrets/actions/ACCESS_TOKEN
# Personal Access Token deleting itself: Probably you commit the token to your GitHub repo, if its the case Github will remove the token immediately, so you need to set your token as a variable environment in your system.

name: "on-push"

on:
   push:
      branches:
         - main
   # pull_request:
      # branches:
         # - main
   # page_build:
   # release:
      # types:
         # - created
   repository_dispatch:
   workflow_dispatch:

jobs:
   on-push:
      name: "On Push"
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash
      steps:
         - name: "[finished] Finish worked"
           shell: bash
           run: |
              echo '${{ join }}'
