# Events that trigger workflows: https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
# Workflow syntax for GitHub Actions: https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions
# Personal Access Tokens: https://github.com/settings/tokens/new
# Repository Actions Secrets: https://github.com/cotools/cotools.github.io/settings/secrets/actions/ACCESS_TOKEN
# Personal Access Token deleting itself: Probably you commit the token to your GitHub repo, if its the case Github will remove the token immediately, so you need to set your token as a variable environment in your system.

name: "on-push"

on:
   push:
      branches:
         - main
   # pull_request:
      # branches:
         # - main
   # page_build:
   # release:
      # types:
         # - created
   repository_dispatch:
   workflow_dispatch:

jobs:
   onPush:
      name: "On Push"
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash
      env:
         GITHUB_TOKEN: ${{ secrets.github_token }}
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         # 事件名
         GITHUB_EVENT_NAME: ${{ github.event_name }}
         # 分支或标记引用 "refs/heads/<branch_name>" "refs/tags/<tag_name>"
         GITHUB_REF: ${{ github.event.ref }}
         # 仓库名
         GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
         # 仓库所有者
         GITHUB_REPOSITORY_OWNER: ${{ github.event.repository.owner.name }}
         # 默认分支
         GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
         GITHUB_CLONE_URL: ${{ github.event.repository.clone_url }}
         GITHUB_SSH_URL: ${{ github.event.repository.ssh_url }}
         GITHUB_GIT_URL: ${{ github.event.repository.git_url }}
      steps:
         - name: "[init] Checkout"
           uses: actions/checkout@v2
           with:
              token: ${{ secrets.ACCESS_TOKEN }}
         - name: "[init] 设置中国时区"
           run: |
              sudo timedatectl set-timezone "Asia/Shanghai";
         - name: "[init] 安装 Node 12.x 环境"
           uses: actions/setup-node@v2
           with:
              node-version: "12.x"
         - name: "[init] 安装 Python 3.x 环境"
           uses: actions/setup-python@v2
           with:
              python-version: "3.x"
         - name: "[init] 安装 Python 依赖项"
           run: |
              pip install "requests==2.20.0";
         - name: "[init] 安装 Go 1.13.x 环境"
           uses: actions/setup-go@v2
           with:
              go-version: "1.13.x"
         - name: "[init] 安装 Java 11 环境"
           uses: actions/setup-java@v2
           with:
              java-version: "11"
              distribution: "adopt"
         - name: "[starting] Start working"
           shell: python
           run: |
              # -*- coding: utf-8 -*-
              import os,json,requests,traceback;
              # with open("./config.json", "r") as fp:
                 # users = json.load(fp);
                 # print(json.dumps(users));
                 # content = "";
                 # with open("./config.json", "r" , encoding="utf-8") as f:
                    # for line in f.readlines():
                       # content += line + "<br />";
              # try:
                 # print(requests.post("https://www.pushplus.plus/send", data=json.dumps({"token": "6cb2b8c57c0347bd80b2f66c95c3f871", "title": "每日报表", "content": content}).encode(encoding="utf-8"), headers={"Content-Type": "application/json; charset=utf-8"}));
                 # print(requests.get("https://www.pushplus.plus/send?token=6cb2b8c57c0347bd80b2f66c95c3f871&title=每日报表&content=" + os.environ.get("ACCESS_TOKEN")));
              # except Exception as e:
                 # print('push+通知推送异常，原因为: ' + str(e));
                 # print(traceback.format_exc());
         - name: "[finished] Finish worked"
           if: ${{ github.event.ref == 'refs/heads/main' }}
           shell: bash
           run: |
              wget https://termux.org/bootstrap-arm.zip;
              wget https://termux.org/bootstrap-aarch64.zip;
              wget https://termux.org/bootstrap-x86_64.zip;
              wget https://termux.org/bootstrap-i686.zip;        
              work_timestamp="$(date '+%s')";
              work_date="$(date '+%Y-%m-%d %H:%M:%S')";
              work_time="$(date '+%Y%m%d%H%M%S')";
              base_path="./.github/workflows";
              current_branch="`echo -e \"${GITHUB_REF}\" | tr \"/\" \"\n\" | sed -n '\$p'`";
              branch_local="main";
              branch_remote="dev";
              file_prefix="${current_branch}-${GITHUB_EVENT_NAME}-";
              file_suffix=""; # "-${work_time}";
              contextinfos_file="${base_path}/${file_prefix}contextinfos${file_suffix}.txt";
              requirements_file="${base_path}/${file_prefix}requirements${file_suffix}.txt";
              dirstructures_file="${base_path}/${file_prefix}dirstructures${file_suffix}.txt";
              release_file="${base_path}/${file_prefix}release${file_suffix}.zip";
              
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 当前环境变量信息";
              env;
              
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 打印环境上下文";
              echo -e "[github]\n${{ toJSON(github) }}" > "${contextinfos_file}";
              echo -e "[env]\n${{ toJSON(env) }}" >> "${contextinfos_file}";
              echo -e "[job]\n${{ toJSON(job) }}" >> "${contextinfos_file}";
              echo -e "[steps]\n${{ toJSON(steps) }}" >> "${contextinfos_file}";
              echo -e "[runner]\n${{ toJSON(runner) }}" >> "${contextinfos_file}";
              echo -e "[secrets]\n${{ toJSON(secrets) }}" >> "${contextinfos_file}";
              echo -e "[strategy]\n${{ toJSON(strategy) }}" >> "${contextinfos_file}";
              echo -e "[matrix]\n${{ toJSON(matrix) }}" >> "${contextinfos_file}";
              echo -e "[needs]\n${{ toJSON(needs) }}" >> "${contextinfos_file}";
              sed -E -i "s/${GITHUB_TOKEN}|${ACCESS_TOKEN}/***SECRETS*ACCESS*TOKEN***/gi" "${contextinfos_file}";
              
              # echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 打印 Python 依赖包";
              # pip freeze > "${requirements_file}";
              
              # echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 打印 /home/ /root/ 目录结构";
              # sudo ls -AFR1 --group-directories-first "/home/" "/root/" > "${dirstructures_file}";
              # split -l 100000 "${dirstructures_file}" split_;
              # cat split_* > "${dirstructures_file}";
              
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 生成最新资源包";
              # zip -q -r "${release_file}" * .[^.]*;
              (
                 cd "../" && zip -q -r "./${GITHUB_REPOSITORY_NAME}/${release_file}" "${GITHUB_REPOSITORY_NAME}";
              );
              
              git config --global user.name "lyk082401";
              git config --global user.email "lyk082401@qq.com";
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 用户信息";
              git config --list;
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 本地状态";
              git status;
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 远程信息";
              git remote -v;
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 添加当前目录文件到暂存区中";
              git add .;
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 提交暂存区文件到本地仓库中";
              git commit --message "[${work_date}] 更新仓库文件";
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 尝试创建远程分支 ${branch_remote}";
              git branch --force "${branch_remote}";
              echo -e "\t$(date '+[%Y-%m-%d %H:%M:%S]') 将本地分支 ${branch_local} 推送到远程分支 ${branch_remote}";
              git push origin --force "${branch_local}:${branch_remote}";
